"""empty message

Revision ID: 634d5e23f0fe
Revises: 3e43eb0cdc56
Create Date: 2024-11-22 10:20:19.291697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634d5e23f0fe'
down_revision = '3e43eb0cdc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('terrain')

    # ### end Alembic commands ###
